version: "3"

services: 
  app:
    # image: php:7.4.25-fpm
    # image: phpswoole/swoole:4.8.0-php7.4
    build: 
      context: ./
      dockerfile: php.dockerfile
      # dockerfile: php-swoole.dockerfile
    # expose: ["9000", '9501']
    expose:
      - "9000"
      - "9501"
    # ports: ["9000", '9501']
    ports:
      - "9000"
      - "9501"
    links:
      - db
      - cache
    depends_on:
      - db
      - cache
    environment:
      - TZ=Asia/Shanghai
    # container_name: app
    volumes: 
      # - ./etc/profile/:/root/
      - ./:/var/www/html
  db:
    # image: mysql:5.7.36
    build: 
      context: ./
      dockerfile: mysql.dockerfile
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    ports: 
      - "3336:3306"
    environment:
      - TZ=Asia/Shanghai
    # container_name: db
    volumes:
      # - ./etc/profile/:/root/
      # - ./etc/mysql/conf.d/my.cnf:/etc/alternatives/my.cnf
      - ./etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
  cache:
    # image: redis:latest
    build:
      context: ./
      dockerfile: redis.dockerfile
    expose:
      - "6379"
    ports:
      - "6379"
    environment:
      - TZ=Asia/Shanghai
    # container_name: cache
    # volumes:
      # - ./etc/profile/:/root/
  web:
    # image: nginx:latest
    build: 
      context: ./
      dockerfile: nginx.dockerfile
    links:
      - app
    depends_on:
      - app
    ports:
      - "8088:80"
    environment:
      # - NGINX_HOST=localhost
      # - NGINX_PORT=80
      - TZ=Asia/Shanghai
    # container_name: web
    volumes:
      - ./etc/profile/:/root/
      - ./:/usr/share/nginx/html
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    # command: [nginx-debug, '-g', 'daemon off;']


